# Generated by Django 4.2.7 on 2023-11-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=255)),
                ("telefone", models.TextField(max_length=255)),
                ("endereco", models.TextField(max_length=255)),
                ("pedido", models.TextField()),
                ("pagamento", models.TextField())
            ],
        ),
    ]
